architecture: standalone
auth:
  enabled: true
  password: "redis-password"
replica:
  replicaCount: 3
service:
  type: ClusterIP
  port: 6379
resources:
  limits:
    cpu: "1000m"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"
