architecture: standalone
auth:
  enabled: true
  password: "redis-password"
replica:
  replicaCount: 2
service:
  type: ClusterIP
  port: 6379
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
