apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: uat
            namespace: redis-uat
            valueFile: values/uat-values.yaml
          - env: prod
            namespace: redis-prod
            valueFile: values/prod-values.yaml
  template:
    metadata:
      name: redis-{{env}}
    spec:
      project: default
      source:
        repoURL: https://github.com/vic0706/TEST_ENV.git   # << 請換成你的 GitLab repo
        targetRevision: HEAD
        path: .
        helm:
          valueFiles:
            - '{{valueFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
