apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: asia-dev-uat
        namespace: redis
        url: https://kubernetes.default.svc
      - cluster: asia-dev
        namespace: redis
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-redis'
    spec:
      project: default
      source:
        repoURL: https://github.com/vic0706/TEST_ENV.git
        targetRevision: main
        path: apps/redis/overlays/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
